language: cpp
os:
  - linux
  dist:
    - xenial
branches:
  only:
    - master
    - fq-dev
    - yz-branch
    - mc-dev
script:
  - git submodule init
  - git submodule update
  - cd minicaffe/build
  - cmake .. -DTEST_ENABLED=ON
  - cmake --build .