language: cpp
os:
  - linux
dist:
  - xenial
branches:
  only:
    - master
    - fq-dev
    - yz-branch
    - mc-dev
before_install:
  - wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_10.1.105-1_amd64.deb
  - sudo dpkg -i cuda-repo-ubuntu1604_10.1.105-1_amd64.deb
  - sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
  - sudo apt-get update
  - sudo apt-get install -y cuda
script:
  - cd minicaffe/build
  - cmake .. -DTEST_ENABLED=ON
  - cmake --build .