language: cpp
os:
  - linux
dist:
  - xenial
branches:
  only:
    - master
    - fq-dev
    - yz-branch
    - mc-dev
before_install:
  - sudo apt-get install -y cuda
script:
  - cd minicaffe/build
  - cmake .. -DTEST_ENABLED=ON
  - cmake --build .