language: cpp
os:
  - linux
branches:
  only:
    - master
    - fq-dev
    - yz-branch
script:
  - git submodule init
  - git submodule update
  - cd minicaffe/build
  - cmake .. -DTEST_ENABLED=ON
  - cmake --build .